//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KryptoChat.VillainServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VillainServiceReference.IVillainService")]
    public interface IVillainService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVillainService/GetVillainName", ReplyAction="http://tempuri.org/IVillainService/GetVillainNameResponse")]
        string GetVillainName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVillainService/GetVillainName", ReplyAction="http://tempuri.org/IVillainService/GetVillainNameResponse")]
        System.Threading.Tasks.Task<string> GetVillainNameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVillainServiceChannel : KryptoChat.VillainServiceReference.IVillainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VillainServiceClient : System.ServiceModel.ClientBase<KryptoChat.VillainServiceReference.IVillainService>, KryptoChat.VillainServiceReference.IVillainService {
        
        public VillainServiceClient() {
        }
        
        public VillainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VillainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VillainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VillainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVillainName() {
            return base.Channel.GetVillainName();
        }
        
        public System.Threading.Tasks.Task<string> GetVillainNameAsync() {
            return base.Channel.GetVillainNameAsync();
        }
    }
}
